// Color constants
export {
  MARKER_COLORS,
  DEFAULT_MARKER_COLOR,
  ITEM_COLORS,
  DEFAULT_ITEM_COLOR,
  DEFAULT_REGION_COLOR,
  DEFAULT_ITEM_COLOR_RGB,
  DEFAULT_REGION_COLOR_RGB,
  TRACK_COLORS,
  DEFAULT_TRACK_COLOR,
} from './colors';

// Layout constants
export {
  PANEL_HEIGHT_COLLAPSED,
  PANEL_HEIGHT_EXPANDED,
  PANEL_TRANSITION_MS,
  STRIP_OVERHEAD_FULL,
  STRIP_OVERHEAD_COMPACT,
  MIN_FADER_PORTRAIT,
  MIN_FADER_LANDSCAPE,
  MAX_FADER_PERCENT,
  MIXER_CONTENT_PADDING,
  TIMELINE_OVERHEAD_NAVIGATE,
  TIMELINE_OVERHEAD_REGIONS,
  TIMELINE_CONTENT_PADDING,
  MIN_TIMELINE_HEIGHT,
  MAX_TIMELINE_PERCENT,
  PHONE_MAX_WIDTH,
  TABLET_MIN_WIDTH,
} from './layout';
